<!DOCTYPE html>
<html>
 <head>
  <meta http-equiv="content-Type" content="text/html; charset=utf-8" />
   <title></title>
<link rel="stylesheet" href="stylesheet22.css">

<style type="text/css">
.div-left{float:left;padding-left:0px;}
.div-rightt{float:right;padding-right:70px;}

.pp
{
background:gray;
}
</style>
</head>
<body>


<div class="pp">

<h1><font color="white">IBM<font></h1></div>
<div class="footer-container">

<div class="div-left"> 
<ul class="footer">
<font color="black">
<h2>IBM  Info</h2>
International Business Machines Corporation (IBM) is an American multinational<br>
 information technology company headquartered in Armonk, New York,with operations<br>
in over 170 countries. The company began in 1911, founded in Endicott, New York,<br>
 as the Computing-Tabulating-Recording Company (CTR) and was renamed <br>
"International Business Machines" in 1924.  <br>IBM produces and sells computer hardware,<br>
 middleware and software, and provides hosting and consulting services in areas <br>
ranging from mainframe computers to nanotechnology. IBM is also a major research <br>
organization, holding the record for most U.S. patents generated by a business <br>
(as of 2019) for 26 consecutive years.Inventions by IBM include the automated <br>
teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card,<br>
 the relational database, the SQL programming language, the UPC barcode, and dynamic<br>
 random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the<br>
dominant computing platform during the 1960s and 1970s. 
</ul>
</div>
<div class="div-right"> 
 <ul class="footer">
<center>

<h2>Company Details</h2>
<h4>IBM's logo:</h4>since 2015
<h4>Founded</h4>
September 4, 1998; 20 years ago in Menlo Park, California

<h4>Key people</h4>
Sundar Pichai (CEO)
Ruth Porat (CFO)
<h4>Website</h4>
google.com
</ul>
</div>


<div class="containerssss">
       <ul>
<center>
<h2>Office Images</h2>

      <li><div class="title"><span><img src="im1.jpg" width="90%" height="70%"></span></div></li>
     <li><div class="title"><span><img src="im2.jpg" width="90%" height="70%"></span></div> </li>
      <li><div class="title"><span><img src="im3.jpg" width="90%" height="70%"></span></div> </li>
      <li><div class="title"><span><img src="im4.jpg" width="90%" height="70%"></span></div> </li>
      <li><div class="title"><span><img src="im5.jpg" width="90%" height="70%"></span></div> </li>
       <li><div class="title"><span><img src="im6.jpg" width="80%" height="60%"></span></div> </li>
      <li><div class="title"><span><img src="im7.jpg" width="90%" height="70%"></span></div> </li>
     <li><div class="title"><span><img src="im8.jpg" width="90%" height="70%"></span></div> </li>
    <li><div class="title"><span><img src="im9.jpg" width="90%" height="70%"></span></div> </li>
      <li><div class="title"><span><img src="im10.jpg" width="90%" height="70%"></span></div> </li>
</ul> 
</center>
</div>
<center>
<a href="ibmcomjob.php">See All Available Jobs</a>
</center>
<img src="/mainproject/f.jpg" width="2%" height="1%">
<img src="/mainproject/t.jpg" width="2%" height="1%">
<img src="/mainproject/i.jpg" width="2%" height="1%">
</div>
</font>
</body>
</html>